### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by colobas** [snowplow/google-cloud-pubsub-example-project#1]
- BINTRAY_SNOWPLOW_GENERIC_USER
- BINTRAY_SNOWPLOW_GENERIC_API_KEY

**Comment by alexanderdean** [comment]
BTW @colobas I fully expect this commit to be flattened into your "Initial commit" prior to release!

**Comment by alexanderdean** [comment]
BTW2 I stubbed https://bintray.com/snowplow/snowplow-generic/google-cloud-dataflow-example-project for you
